language: node_js
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: caef372a579656c0ab56ded398fa586fd0431613
  keep-history: true
  on:
    branch: master